# This rule is not used by the project ocphealthcheckinf itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to monitoring.spark.co.nz resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ocphealthcheckinf
    app.kubernetes.io/managed-by: kustomize
  name: ocphealthcheck-viewer-role
rules:
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - ocphealthchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - ocphealthchecks/status
  verbs:
  - get
