# This rule is not used by the project ocphealthcheckinf itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over monitoring.spark.co.nz.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ocphealthcheckinf
    app.kubernetes.io/managed-by: kustomize
  name: ocphealthcheck-admin-role
rules:
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - ocphealthchecks
  verbs:
  - '*'
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - ocphealthchecks/status
  verbs:
  - get
