---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certm.spark.co.nz
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - ocphealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - ocphealthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - ocphealthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nmstate.io
  resources:
  - nodenetworkconfigurationpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  - clusterserviceversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trident.netapp.io
  resources:
  - tridentbackendconfigs
  - tridentbackends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tuned.openshift.io
  resources:
  - profiles
  verbs:
  - get
  - list
  - watch
